name: flutter_netwok_module
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  connectivity_plus: ^6.1.4
  dio: ^5.8.0+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter

  flutter_core:
    git:
      url: https://github.com/Risav25Pokhrel/flutter_core.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter: